<a href="https://colab.research.google.com/github/sk-shahsi/Deep_learning_code/blob/master/Dl_Using_Tenserflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import layers
import pandas as pd

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
x = df[['soil_moisture','sunlight_hours','temperature_c']]
y = df['needs_water']

In [5]:
x_min = x.min()
x_max = x.max()
x_scaled = (x-x_min)/(x_max-x_min+1e-8)

In [6]:
x_scaled

    soil_moisture  sunlight_hours  temperature_c
0        0.066667        0.727273         0.9375
1        0.133333        0.636364         0.6875
2        0.200000        0.545455         0.4375
3        0.266667        0.272727         0.1875
4        0.466667        0.636364         0.5625
5        0.733333        0.818182         0.6875
6        0.400000        0.181818         0.0000
7        0.173333        0.818182         0.1875
8        0.533333        1.000000         1.0000
9        0.000000        0.363636         0.3125
10       1.000000        0.727273         0.8750
11       0.293333        0.909091         0.8750
12       0.666667        0.090909         0.1250
13       0.866667        0.454545         0.3750
14       0.093333        0.000000         0.0625
15       0.333333        0.727273         0.6250

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [8]:
model = keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41 (164.00 B)

 Trainable params: 41 (164.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [11]:
from re import VERBOSE
from sklearn.utils import validation
history = model.fit(x_train.values,y_train.values,
                    validation_data=(x_test.values,y_test.values),
                    epochs=100,batch_size = 4,verbose=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 305ms/step - accuracy: 0.5833 - loss: 2.2012 - val_accuracy: 0.7500 - val_loss: 0.5054
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5833 - loss: 1.3313 - val_accuracy: 0.7500 - val_loss: 0.6043
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.4167 - loss: 1.1061 - val_accuracy: 0.7500 - val_loss: 0.7679
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.2500 - loss: 0.9542 - val_accuracy: 0.2500 - val_loss: 1.4744
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.8484 - val_accuracy: 0.2500 - val_loss: 1.4510
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4167 - loss: 0.8674 - val_accuracy: 0.2500 - val_loss: 1.6412
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.7623 - val_accuracy: 1.0000 - val_loss: 0.6058
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.7678 - val_accuracy: 1.0000 - val_loss: 0.5994
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.6908 - val_accuracy: 0.2500 - val_loss: 1.0871
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6901 - val_accuracy: 0.7500 - val_loss: 0.5689
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4167 - loss: 1.2322 - val_accuracy: 0.7500 - val_loss: 0.8929
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4167 - loss: 0.9010 - val_accuracy: 0.2500 - val_loss: 1.9683
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4167 - loss: 1.2547 - val_accuracy: 0.2500 - val_loss: 1.2262
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2500 - loss: 1.3287 - val_accuracy: 0.2500 - val_loss: 0.7092
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7544 - val_accuracy: 0.7500 - val_loss: 0.6242
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.2500 - loss: 0.9281 - val_accuracy: 0.2500 - val_loss: 0.7952
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6901 - val_accuracy: 0.2500 - val_loss: 1.0302
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.9815 - val_accuracy: 0.2500 - val_loss: 0.7171
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6975 - val_accuracy: 0.7500 - val_loss: 0.6187
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5833 - loss: 0.6835 - val_accuracy: 0.2500 - val_loss: 1.0133
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4167 - loss: 0.8026 - val_accuracy: 0.2500 - val_loss: 0.9078
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4167 - loss: 0.8102 - val_accuracy: 0.2500 - val_loss: 0.9587
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 0.6872 - val_accuracy: 0.2500 - val_loss: 0.8591
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5833 - loss: 0.6906 - val_accuracy: 0.2500 - val_loss: 1.0455
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5833 - loss: 0.7285 - val_accuracy: 0.7500 - val_loss: 0.6773
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.7494 - val_accuracy: 0.2500 - val_loss: 1.1896
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5833 - loss: 0.7703 - val_accuracy: 0.2500 - val_loss: 0.7581
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7122 - val_accuracy: 0.5000 - val_loss: 0.6958
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.7321 - val_accuracy: 0.2500 - val_loss: 1.0913
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4167 - loss: 0.8822 - val_accuracy: 0.2500 - val_loss: 1.0392
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.7351 - val_accuracy: 0.7500 - val_loss: 0.5838
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.2500 - loss: 0.8920 - val_accuracy: 0.2500 - val_loss: 0.8477
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.7641 - val_accuracy: 0.7500 - val_loss: 0.5919
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4167 - loss: 0.7412 - val_accuracy: 0.5000 - val_loss: 0.6760
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.3333 - loss: 0.8475 - val_accuracy: 0.2500 - val_loss: 1.2049
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6799 - val_accuracy: 0.5000 - val_loss: 0.6969
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6743 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.6757 - val_accuracy: 0.2500 - val_loss: 0.7286
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.6534 - val_accuracy: 0.2500 - val_loss: 0.9323
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4167 - loss: 0.8004 - val_accuracy: 0.2500 - val_loss: 1.0292
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.8352 - val_accuracy: 0.7500 - val_loss: 0.6335
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6688 - val_accuracy: 0.2500 - val_loss: 0.8930
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6684 - val_accuracy: 0.2500 - val_loss: 0.9293
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6763 - val_accuracy: 0.2500 - val_loss: 0.9694
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6512 - val_accuracy: 0.5000 - val_loss: 0.6920
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6533 - val_accuracy: 0.2500 - val_loss: 0.7570
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4167 - loss: 0.7416 - val_accuracy: 0.2500 - val_loss: 0.8138
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6501 - val_accuracy: 0.2500 - val_loss: 0.8516
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6779 - val_accuracy: 0.2500 - val_loss: 0.8135
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6445 - val_accuracy: 0.5000 - val_loss: 0.7000
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.7786 - val_accuracy: 0.2500 - val_loss: 1.3137
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6980 - val_accuracy: 0.5000 - val_loss: 0.6705
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.6364 - val_accuracy: 0.2500 - val_loss: 0.9544
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6690 - val_accuracy: 0.0000e+00 - val_loss: 0.7473
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6536 - val_accuracy: 0.2500 - val_loss: 0.8102
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.3333 - loss: 0.8066 - val_accuracy: 0.2500 - val_loss: 0.8198
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6861 - val_accuracy: 0.5000 - val_loss: 0.6652
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4167 - loss: 0.7054 - val_accuracy: 0.2500 - val_loss: 1.2307
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.7002 - val_accuracy: 0.2500 - val_loss: 0.8692
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6951 - val_accuracy: 0.5000 - val_loss: 0.6657
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4167 - loss: 0.7392 - val_accuracy: 0.5000 - val_loss: 0.6838
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.8014 - val_accuracy: 0.5000 - val_loss: 0.6982
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9167 - loss: 0.6377 - val_accuracy: 0.2500 - val_loss: 0.8875
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6805 - val_accuracy: 0.5000 - val_loss: 0.6834
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.8568 - val_accuracy: 0.2500 - val_loss: 0.8265
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.8969 - val_accuracy: 0.2500 - val_loss: 0.7847
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6668 - val_accuracy: 0.2500 - val_loss: 0.8060
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6582 - val_accuracy: 0.2500 - val_loss: 0.8293
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.6911 - val_accuracy: 0.2500 - val_loss: 0.8910
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6360 - val_accuracy: 0.2500 - val_loss: 0.8015
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6872 - val_accuracy: 0.2500 - val_loss: 1.1327
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6535 - val_accuracy: 0.2500 - val_loss: 0.8382
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6298 - val_accuracy: 0.2500 - val_loss: 0.8545
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6508 - val_accuracy: 0.5000 - val_loss: 0.7437
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.6307 - val_accuracy: 0.2500 - val_loss: 0.9078
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6494 - val_accuracy: 0.2500 - val_loss: 0.9693
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6223 - val_accuracy: 0.2500 - val_loss: 0.8463
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6447 - val_accuracy: 0.2500 - val_loss: 0.8127
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.7035 - val_accuracy: 0.5000 - val_loss: 0.7067
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.6915 - val_accuracy: 0.2500 - val_loss: 0.9019
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6923 - val_accuracy: 0.5000 - val_loss: 0.7200
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7500 - loss: 0.6335 - val_accuracy: 0.2500 - val_loss: 0.9102
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.3333 - loss: 0.7728 - val_accuracy: 0.2500 - val_loss: 1.2113
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6364 - val_accuracy: 0.0000e+00 - val_loss: 0.8160
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6302 - val_accuracy: 0.2500 - val_loss: 0.9584
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6818 - val_accuracy: 0.2500 - val_loss: 1.0511
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.7246 - val_accuracy: 0.0000e+00 - val_loss: 0.8092
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.6795 - val_accuracy: 0.5000 - val_loss: 0.7543
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6362 - val_accuracy: 0.0000e+00 - val_loss: 0.8155
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6034 - val_accuracy: 0.2500 - val_loss: 0.9283
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6020 - val_accuracy: 0.2500 - val_loss: 0.9114
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6513 - val_accuracy: 0.5000 - val_loss: 0.7577
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.7073 - val_accuracy: 0.2500 - val_loss: 0.9187
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6519 - val_accuracy: 0.2500 - val_loss: 1.0113
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6110 - val_accuracy: 0.0000e+00 - val_loss: 0.8601
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6377 - val_accuracy: 0.2500 - val_loss: 0.8827
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6107 - val_accuracy: 0.0000e+00 - val_loss: 0.8606
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6862 - val_accuracy: 0.2500 - val_loss: 0.9830
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.7178 - val_accuracy: 0.2500 - val_loss: 0.9406
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5928 - val_accuracy: 0.2500 - val_loss: 0.9324

In [12]:
from keras import optimizers

In [13]:
opt = optimizers.SGD(learning_rate=0.01,momentum=0.9)